name: music_shop_erp
description: ERP for MusicShopRD with persistence and exports.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.2.2
  intl: ^0.19.0
  pdf: ^3.10.7
  printing: 5.12.0
  excel: ^4.0.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
