name: music_shop_erp
description: ERP for MusicShopRD with persistence and exports.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  pdf: ^3.10.7
  printing: 5.12.0
  excel: ^4.0.2
  path_provider: ^2.1.1
  uuid: ^4.2.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dependency_overrides:
  path_provider_foundation: 2.4.0
  shared_preferences_foundation: 2.3.5
